eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
    instance:
      prefer-ip-address: true
    register-with-eureka: true

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}/:9411/
    sender:
      type: rabbit
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
