server:
  port: ${PORT:0}

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: vuelosdb
      host: localhost
      port: 27017
  jpa:
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

logging:
  level:
    sql: debug